# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dpc-container-app

on:
  pull:
    branches:
        - main
    
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Tree view
      run: |
          ls -la
          sudo apt-get install -y tree
          tree .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: vijayrr2208
        password: VIshal@2410

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: vijayrr2208/docker-repo:v1
        file: ./Dockerfile
